backend:
  name: git-gateway
  branch: main

media_folder: static/images
public_folder: ../../static/images/

collections:
  - name: events
    preview: false
    label: Events
    folder: content/events
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Time", name: "time", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
  - name: landing
    preview: true
    label: Home
    folder: content/landing
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Headline", name: "headline", widget: "string" }
      - { label: "Position", name: "position", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
