backend:
  name: git-gateway
  branch: main

media_folder: static/images
public_folder: ../../static/images/

media_library:
  name: cloudinary
  config:
    cloud_name: dielbqrvv
    # public api key
    api_key: 515688223637771
    default_transformations:
      secure: true
      cdn_subdomain: true
      use_secure_url: true
      quality: 80
      crop: fill
      gravity: auto
      fetch_format: auto
      responsive: true
      breakpoints: [320, 640, 768, 1024, 1280]

collections:
  - name: events
    preview: false
    label: Events
    folder: content/events
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Start", name: "start", widget: "datetime" }
      - { label: "End", name: "end", widget: "datetime" }
      - { label: "AllDay", name: "allDay", widget: "boolean" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
  - name: carousel
    preview: true
    label: Carousel Images
    folder: content/carousel
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Position", name: "position", widget: "number" }
      - { label: "Headline", name: "headline", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: about
    preview: false
    label: About
    folder: content/about
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Instagram", name: "instagram", widget: "string" }
      - { label: "InstagramLink", name: "instagramLink", widget: "string" }
      - { label: "Facebook", name: "facebook", widget: "string" }
      - { label: "FacebookLink", name: "facebookLink", widget: "string" }
      - { label: "About", name: "about", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
  - name: services
    preview: false
    label: Services
    folder: content/services
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "description", name: "description", widget: "markdown" }
  - name: images
  - preview: false
    label: Social Media
    folder: content/media
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image Link", name: "link", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
