backend:
  name: git-gateway
  branch: main

media_folder: static/images
public_folder: ../../static/images/

media_library:
  name: cloudinary
  config:
    cloud_name: dielbqrvv
    # public api key
    api_key: 515688223637771
    default_transformations:
      secure: true
      cdn_subdomain: true
      use_secure_url: true
      quality: 80
      crop: fill
      gravity: auto
      fetch_format: auto
      responsive: true
      breakpoints: [320, 640, 768, 1024, 1280]

collections:
  - name: events
    preview: false
    label: Events
    folder: content/events
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Time", name: "time", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
  - name: carousel
    preview: true
    label: Carousel Images
    folder: content/carousel
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Position", name: "position", widget: "number" }
      - { label: "Headline", name: "headline", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: about
    preview: false
    label: About
    folder: content/about
    create: true
    slug: "{{slug}}"
        fields:
      - { label: "About", name: "about", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
    
    
